#!/bin/bash

rm -Rf bin
./make

CLASSPATH=""
if [ $OSTYPE == "msys" ]; then
  CLASSPATH="bin;lib/junit-4.11.jar;lib/hamcrest-core-1.3.jar"
else
  CLASSPATH="bin:lib/junit-4.11.jar:lib/hamcrest-core-1.3.jar"
fi

java -cp $CLASSPATH org.junit.runner.JUnitCore \
  com.growingwiththeweb.algorithms.sorting.BubbleSortTest \
  com.growingwiththeweb.algorithms.sorting.BubbleSortOptimisedTest \
  com.growingwiththeweb.algorithms.sorting.BucketSortTest \
  com.growingwiththeweb.algorithms.sorting.CountingSortTest \
  com.growingwiththeweb.algorithms.sorting.InsertionSortTest \
  com.growingwiththeweb.algorithms.sorting.MergeSortTest \
  com.growingwiththeweb.algorithms.sorting.MergeSortBottomUpTest \
  com.growingwiththeweb.algorithms.sorting.MergeSortNaturalTest \
  com.growingwiththeweb.algorithms.sorting.QuicksortTest \
  com.growingwiththeweb.algorithms.sorting.QuicksortRandomTest \
  com.growingwiththeweb.algorithms.sorting.SelectionSortTest \
  com.growingwiththeweb.datastructures.BinaryHeapTest \
  com.growingwiththeweb.datastructures.RedBlackTreeTest \
  com.growingwiththeweb.designpatterns.singleton.LazyLoadingSingletonTest \
  com.growingwiththeweb.designpatterns.singleton.SingletonTest
