#!/bin/bash

rm -Rf bin
./make

CLASSPATH=""
if [ "$1" = "win" ]; then
  CLASSPATH="bin;lib/junit-4.11.jar;lib/hamcrest-core-1.3.jar"
else
  CLASSPATH="bin:lib/junit-4.11.jar:lib/hamcrest-core-1.3.jar"
fi

java -cp $CLASSPATH org.junit.runner.JUnitCore \
  com.growingwiththeweb.dataStructures.BinaryHeapTest \
  com.growingwiththeweb.dataStructures.RedBlackTreeTest
